### ISSUE TITLE
Vec[Unit] throws

### ISSUE THREAD

**Issue by pityka** [pityka/saddle#324]
`org.saddle.Vec(()).map(println)` throws 

```
java.lang.IllegalArgumentException
  at java.lang.reflect.Array.newArray(Native Method)
  at java.lang.reflect.Array.newInstance(Array.java:75)
  at scala.reflect.ClassTag.newArray(ClassTag.scala:66)
  at scala.reflect.ClassTag.newArray$(ClassTag.scala:65)
  at org.saddle.scalar.ScalarTagAny.newArray(ScalarTagAny.scala:23)
  at scala.collection.IterableOnceOps.toArray(IterableOnce.scala:1278)
  at scala.collection.IterableOnceOps.toArray$(IterableOnce.scala:1276)
  at scala.collection.AbstractIterable.toArray(Iterable.scala:919)
  at org.saddle.Vec$.apply(Vec.scala:52)
```

Even if not very useful, it should not blow up.

**Comment by pityka** [comment]
Fixed in recent changes by making Vec[Unit] is impossible to compile. ScalarTag[AnyVal] was removed.
